/*
# Create Loyalty Wallet Platform Schema

## Overview
Creates the full database schema for a multi-tenant digital loyalty wallet platform.
The app is a NestJS backend using Prisma ORM with its own JWT auth (not Supabase auth).
Tables use TEXT-based CUID primary keys (generated by Prisma client) to match the Prisma schema.

## New Tables
1. `companies` — Tenant root: restaurants/brands with branding (colors, logo, hero image), slug, contact info
2. `programs` — Loyalty programs (POINTS or STAMPS) belonging to a company, with flexible JSON settings
3. `users` — App users (customers + staff), email/password auth via NestJS, optional Google/Apple OAuth IDs
4. `memberships` — A user's enrollment in a program: wallet ID, balance, status. Unique per user+program
5. `loyalty_history` — Audit log of every balance change (earn, redeem, adjust, etc.) with actor tracking
6. `wallet_passes` — Tracks Google/Apple wallet pass state per membership (external ID, sync status, errors)

## Enums
- ProgramType: POINTS | STAMPS
- MembershipStatus: ACTIVE | INACTIVE | SUSPENDED | DELETED
- LoyaltyEventType: JOIN | EARN | REDEEM | ADJUST | REFUND | EXPIRE | ADMIN_OVERRIDE | WEBHOOK
- WalletProviderType: GOOGLE | APPLE
- WalletPassStatus: PENDING | ACTIVE | UPDATED | FAILED | REVOKED

## Relationships
- Company 1→N Programs, Memberships
- Program 1→N Memberships
- User 1→N Memberships
- Membership 1→N LoyaltyHistory
- Membership 1→1 WalletPass

## Security (RLS)
RLS is enabled on all tables. Since this app uses NestJS + Prisma with its own JWT auth
(not Supabase auth), the backend connects with the service role key which bypasses RLS.
Policies are set to allow anon+authenticated access as a baseline — the NestJS backend
enforces authorization at the application layer (company scoping, JWT user identity).

## Notes
1. Primary keys are TEXT (CUIDs generated by Prisma client at insert time)
2. Timestamps use TIMESTAMP(3) to match Prisma's default precision
3. All foreign keys use ON DELETE CASCADE to match Prisma schema
4. Unique constraints: company slug, user email, membership walletId, user+program per membership
5. Indexes on all frequently-queried columns (slug, companyId, walletId, userId, email, externalId, createdAt)
*/

-- ─────────────────────────────────────────────
-- Enums
-- ─────────────────────────────────────────────
CREATE TYPE "ProgramType" AS ENUM ('POINTS', 'STAMPS');

CREATE TYPE "MembershipStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'DELETED');

CREATE TYPE "LoyaltyEventType" AS ENUM ('JOIN', 'EARN', 'REDEEM', 'ADJUST', 'REFUND', 'EXPIRE', 'ADMIN_OVERRIDE', 'WEBHOOK');

CREATE TYPE "WalletProviderType" AS ENUM ('GOOGLE', 'APPLE');

CREATE TYPE "WalletPassStatus" AS ENUM ('PENDING', 'ACTIVE', 'UPDATED', 'FAILED', 'REVOKED');

-- ─────────────────────────────────────────────
-- companies
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "companies" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "logoUrl" TEXT,
    "primaryColor" TEXT DEFAULT '#1a73e8',
    "secondaryColor" TEXT DEFAULT '#ffffff',
    "accentColor" TEXT,
    "heroImageUrl" TEXT,
    "website" TEXT,
    "supportEmail" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "companies_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "companies_slug_key" ON "companies"("slug");
CREATE INDEX IF NOT EXISTS "companies_slug_idx" ON "companies"("slug");

-- ─────────────────────────────────────────────
-- programs
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "programs" (
    "id" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "type" "ProgramType" NOT NULL,
    "description" TEXT,
    "logoUrl" TEXT,
    "heroImageUrl" TEXT,
    "primaryColor" TEXT,
    "secondaryColor" TEXT,
    "settings" JSONB NOT NULL DEFAULT '{}',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "programs_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "programs_companyId_idx" ON "programs"("companyId");
CREATE UNIQUE INDEX IF NOT EXISTS "programs_companyId_slug_key" ON "programs"("companyId", "slug");

-- ─────────────────────────────────────────────
-- users
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "users" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "emailVerified" TIMESTAMP(3),
    "name" TEXT,
    "image" TEXT,
    "googleId" TEXT,
    "appleId" TEXT,
    "passwordHash" TEXT,
    "locale" TEXT NOT NULL DEFAULT 'en',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "users_email_key" ON "users"("email");
CREATE UNIQUE INDEX IF NOT EXISTS "users_googleId_key" ON "users"("googleId");
CREATE UNIQUE INDEX IF NOT EXISTS "users_appleId_key" ON "users"("appleId");
CREATE INDEX IF NOT EXISTS "users_email_idx" ON "users"("email");

-- ─────────────────────────────────────────────
-- memberships
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "memberships" (
    "id" TEXT NOT NULL,
    "walletId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "programId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "balance" INTEGER NOT NULL DEFAULT 0,
    "status" "MembershipStatus" NOT NULL DEFAULT 'ACTIVE',
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "memberships_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "memberships_walletId_key" ON "memberships"("walletId");
CREATE INDEX IF NOT EXISTS "memberships_companyId_idx" ON "memberships"("companyId");
CREATE INDEX IF NOT EXISTS "memberships_walletId_idx" ON "memberships"("walletId");
CREATE INDEX IF NOT EXISTS "memberships_userId_idx" ON "memberships"("userId");
CREATE UNIQUE INDEX IF NOT EXISTS "memberships_userId_programId_key" ON "memberships"("userId", "programId");

-- ─────────────────────────────────────────────
-- loyalty_history
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "loyalty_history" (
    "id" TEXT NOT NULL,
    "membershipId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "type" "LoyaltyEventType" NOT NULL,
    "amount" INTEGER NOT NULL,
    "previousBalance" INTEGER NOT NULL,
    "newBalance" INTEGER NOT NULL,
    "reason" TEXT,
    "actorId" TEXT,
    "actorType" TEXT,
    "metadata" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "loyalty_history_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "loyalty_history_membershipId_idx" ON "loyalty_history"("membershipId");
CREATE INDEX IF NOT EXISTS "loyalty_history_companyId_idx" ON "loyalty_history"("companyId");
CREATE INDEX IF NOT EXISTS "loyalty_history_createdAt_idx" ON "loyalty_history"("createdAt");

-- ─────────────────────────────────────────────
-- wallet_passes
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "wallet_passes" (
    "id" TEXT NOT NULL,
    "membershipId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "provider" "WalletProviderType" NOT NULL,
    "externalId" TEXT NOT NULL,
    "saveUrl" TEXT,
    "status" "WalletPassStatus" NOT NULL DEFAULT 'PENDING',
    "lastSyncAt" TIMESTAMP(3),
    "lastError" TEXT,
    "lastPayload" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "wallet_passes_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "wallet_passes_membershipId_key" ON "wallet_passes"("membershipId");
CREATE INDEX IF NOT EXISTS "wallet_passes_companyId_idx" ON "wallet_passes"("companyId");
CREATE INDEX IF NOT EXISTS "wallet_passes_externalId_idx" ON "wallet_passes"("externalId");

-- ─────────────────────────────────────────────
-- Foreign Keys
-- ─────────────────────────────────────────────
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'programs_companyId_fkey') THEN
    ALTER TABLE "programs" ADD CONSTRAINT "programs_companyId_fkey"
      FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'memberships_userId_fkey') THEN
    ALTER TABLE "memberships" ADD CONSTRAINT "memberships_userId_fkey"
      FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'memberships_programId_fkey') THEN
    ALTER TABLE "memberships" ADD CONSTRAINT "memberships_programId_fkey"
      FOREIGN KEY ("programId") REFERENCES "programs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'memberships_companyId_fkey') THEN
    ALTER TABLE "memberships" ADD CONSTRAINT "memberships_companyId_fkey"
      FOREIGN KEY ("companyId") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'loyalty_history_membershipId_fkey') THEN
    ALTER TABLE "loyalty_history" ADD CONSTRAINT "loyalty_history_membershipId_fkey"
      FOREIGN KEY ("membershipId") REFERENCES "memberships"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'wallet_passes_membershipId_fkey') THEN
    ALTER TABLE "wallet_passes" ADD CONSTRAINT "wallet_passes_membershipId_fkey"
      FOREIGN KEY ("membershipId") REFERENCES "memberships"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- ─────────────────────────────────────────────
-- Row Level Security
-- This app uses NestJS + Prisma with its own JWT auth.
-- The backend connects with the service role key (bypasses RLS).
-- Policies allow anon+authenticated as a baseline; authorization
-- is enforced at the NestJS application layer.
-- ─────────────────────────────────────────────
ALTER TABLE "companies" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "programs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "memberships" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "loyalty_history" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "wallet_passes" ENABLE ROW LEVEL SECURITY;

-- companies policies
DROP POLICY IF EXISTS "anon_select_companies" ON "companies";
CREATE POLICY "anon_select_companies" ON "companies" FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_companies" ON "companies";
CREATE POLICY "anon_insert_companies" ON "companies" FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_companies" ON "companies";
CREATE POLICY "anon_update_companies" ON "companies" FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_companies" ON "companies";
CREATE POLICY "anon_delete_companies" ON "companies" FOR DELETE
  TO anon, authenticated USING (true);

-- programs policies
DROP POLICY IF EXISTS "anon_select_programs" ON "programs";
CREATE POLICY "anon_select_programs" ON "programs" FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_programs" ON "programs";
CREATE POLICY "anon_insert_programs" ON "programs" FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_programs" ON "programs";
CREATE POLICY "anon_update_programs" ON "programs" FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_programs" ON "programs";
CREATE POLICY "anon_delete_programs" ON "programs" FOR DELETE
  TO anon, authenticated USING (true);

-- users policies
DROP POLICY IF EXISTS "anon_select_users" ON "users";
CREATE POLICY "anon_select_users" ON "users" FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_users" ON "users";
CREATE POLICY "anon_insert_users" ON "users" FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_users" ON "users";
CREATE POLICY "anon_update_users" ON "users" FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_users" ON "users";
CREATE POLICY "anon_delete_users" ON "users" FOR DELETE
  TO anon, authenticated USING (true);

-- memberships policies
DROP POLICY IF EXISTS "anon_select_memberships" ON "memberships";
CREATE POLICY "anon_select_memberships" ON "memberships" FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_memberships" ON "memberships";
CREATE POLICY "anon_insert_memberships" ON "memberships" FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_memberships" ON "memberships";
CREATE POLICY "anon_update_memberships" ON "memberships" FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_memberships" ON "memberships";
CREATE POLICY "anon_delete_memberships" ON "memberships" FOR DELETE
  TO anon, authenticated USING (true);

-- loyalty_history policies
DROP POLICY IF EXISTS "anon_select_loyalty_history" ON "loyalty_history";
CREATE POLICY "anon_select_loyalty_history" ON "loyalty_history" FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_loyalty_history" ON "loyalty_history";
CREATE POLICY "anon_insert_loyalty_history" ON "loyalty_history" FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_loyalty_history" ON "loyalty_history";
CREATE POLICY "anon_update_loyalty_history" ON "loyalty_history" FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_loyalty_history" ON "loyalty_history";
CREATE POLICY "anon_delete_loyalty_history" ON "loyalty_history" FOR DELETE
  TO anon, authenticated USING (true);

-- wallet_passes policies
DROP POLICY IF EXISTS "anon_select_wallet_passes" ON "wallet_passes";
CREATE POLICY "anon_select_wallet_passes" ON "wallet_passes" FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_wallet_passes" ON "wallet_passes";
CREATE POLICY "anon_insert_wallet_passes" ON "wallet_passes" FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_wallet_passes" ON "wallet_passes";
CREATE POLICY "anon_update_wallet_passes" ON "wallet_passes" FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_wallet_passes" ON "wallet_passes";
CREATE POLICY "anon_delete_wallet_passes" ON "wallet_passes" FOR DELETE
  TO anon, authenticated USING (true);
